### PR TITLE
Adds Routes Command

### PR DESCRIPTION
**Pull request by eliasjpr**
# Shows Application Routes
> This is a clone of this PR https://github.com/Amber-Crystal/amber_cmd/pull/20
> As a Developer I want to be able to see the available routes defined for my application.

Issue https://github.com/Amber-Crystal/amber_cmd/issues/2
Depends https://github.com/Amber-Crystal/amber/pull/104
### Command

```bash
amber routes
```
### Example Output
```bash
Available routes For Your App Name
+-----------+-------------------+--------------------+------------------------+
| HTTP Verb | Controller#Action | Helper (url, path) | Resource               |
+-----------+-------------------+--------------------+------------------------+
| GET       | photos#index      | photos_url/path    | /photos, /photos/index |
+-----------+-------------------+--------------------+------------------------+
| GET       | photos#new        | new_photo_url/path | /photos/new            |
+-----------+-------------------+--------------------+------------------------+
```

### Final Output

screen shot 2017-06-08 at 10 11 42 pm

### Test
- Pull down Amber-Crystal/amber_cmd#21
- Checkout the branch
- Run make
- Then
```bash
amber new blog
cd blog
shards install
amber routes

# then 
amber g scaffold Post title:string
amber routes
```

### CODE REVIEW

**Comment by eliasjpr** [comment]
Renamed branch.

**Comment by eliasjpr** [comment]
@drujensen the changes in this PR depends on the https://github.com/Amber-Crystal/amber/pull/104 PR they are kind of related since this PR (https://github.com/Amber-Crystal/amber/pull/104) adds the functionality to get all routes. Also, I did had an error on the PORT that was being passed as string. I have corrected and updated the PR description above.

**Comment by elorest** [comment]
Another issue I just found with this is that if controllers are referencing models they're not being required so it errors there.

**Comment by eliasjpr** [comment]
:( that means we have to load the entire app to get the routes :(

**Comment by eliasjpr** [comment]
This is ready for another look. 

- Prints the project routes 
- Takes avg 3 secs on my laptop
- Removes PORT and AMBER_ENV vars

Please review so we can ship this

**Pull request merged**
