### PR TITLE
added application_controller to load before other controllers.

### PR DESCRIPTION
**Pull request by elorest**
1. Changed load order so that `application_controller` loads before other controllers that depend on it. 
2. Removed the line that loads views since a macro looks at those and generates a string builder with the render option.
3. Cleaned up tests and added `ensure` and `after_each` to make sure test directory is deleted.
4. Added test that failed when files were loaded in the wrong order, fixed it and they passed. TDD 

Issue: https://github.com/Amber-Crystal/amber_cmd/issues/53

### CODE REVIEW

**Comment by elorest** [comment]
All we're really testing at this point in the generators are that the files are created as expected. To actually test things like load order we would have to generate complete projects and then run them. It's possible that this is something we should do anyway. When the amber_spec project is actually fleshed out we could just run the generated tests, which will be nice. Unfortunately tests usually load their own files for testing which could allow for them to pass while the actual app doesn't or visa versa.

**Comment by elorest** [comment]
I think @drujensen was working on the `amber_spec` project. Maybe we should pair on this.

**Comment by elorest** [comment]
I'll merge this in a few hours if there are no objections by then.

**Comment by eliasjpr** [comment]
I would really think we should write a test for this to safeguard us

**Comment by elorest** [comment]
Ok I think you're right. I have an idea.

**Comment by elorest** [comment]
Done! 👍

**Pull request merged**
