### PR TITLE
Bumped after ecr fix and removed vestigial code.

### PR DESCRIPTION
**Pull request by elorest**
Bumped version so that @ultra2mh ecr would work when he updated shards.

Removed sidekiq from shard.yaml.ecr as approved by @drujensen since it should only be there when jobs are generated.

Removed index action from application_controller as it shouldn't be there.

### CODE REVIEW

**Comment by eliasjpr** [comment]
With this bump we have to also update https://github.com/Amber-Crystal/homebrew-amber

**Comment by elorest** [comment]
I wonder if there is a way to automate that or just pull the last tag

**Comment by eliasjpr** [comment]
So I notice that none of our releases have a title and notes, we should at least have a title and add some release notes. This allows for GitHub to mark the latest release which I think then we can use in then use https://github.com/Amber-Crystal/amber_cmd/releases/latest to get the latest release easily from within the brew formula

**Comment by elorest** [comment]
Good point. I believe all of them at least have a title and description even if it's meaningless.

**Comment by elorest** [comment]
@drujensen Hmmm. I wasn't aware that jobs had been merged yet. When we talked a couple days ago you were surprised that sidekiq was in the shard.yml.ecr. I thought that when jobs got merged it was going to handle adding it if needed.

**Pull request merged**
