### PR TITLE
Outputs a better version string

### PR DESCRIPTION
**Pull request by eliasjpr**
Currently the `amber --version` only outputs `0.1.13` which does not look elegant. 

To correct that this PR adds a little more detail to the print output.
With these changes the final output looks like `Amber CMD (www.ambercr.io) - v0.1.13`

### CODE REVIEW

**Comment by eliasjpr** [comment]
Should we print CMD or CLI?
- Amber CMD (www.ambercr.io) - v0.1.13
- Amber CLI (www.ambercr.io) - v0.1.13

**Comment by eliasjpr** [comment]
I was thinking of having the url set it and forget it, is going to be a while before we have a complete www.ambercr.io

**Comment by elorest** [comment]
Ok remove `www` and lets merge it. We could probably at least get some framework specific stuff up on the page pretty quick even if its just a simple getting started block. 

`brew install amber_url`
`amber new project`

**Comment by eliasjpr** [comment]
👍

**Pull request merged**
